import Link from 'next/link';
import { Header } from 'components/Header';
import { Slider } from 'components/Slider';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Carros Top Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <Slider />
      <div className='container mt-4'>
        <div className='row bg-light rounded-3 p-5 d-flex  align-items-center g-3'>
          <div className='col-6 col-sm-6 col-md-6 col-lg-4'>
            <Link href={'/products'}>
              <a className='btn btn-primary fw-bold text-uppercase px-sm-5 px-md-5'>
                Ver Catálago
              </a>
            </Link>
          </div>
          <div className='col-6 col-sm-6 col-md-6 col-lg-8'>
            <h3 className='lead fs-5 text-dark'>Comece agora a navegar</h3>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
